### ISSUE TITLE
macOS 10.15 Compatibility 

### ISSUE THREAD

**Issue by Husovschi** [notthebee/t440p-hackintosh#1]
Will this be updated for macOS Catalina or is it already compatible?

**Comment by notthebee** [comment]
I don't own the device anymore, but feel free to check if it's compatible and create a PR

**Comment by purpose-pending** [comment]
> Will this be updated for macOS Catalina or is it already compatible?

I tried updating the night Catalina came out without updating Clover (Clover Configurator would not update it for some reason) and I wasn't able to boot system after update. So I'd advice at least updating Clover first and then trying out.

**Comment by notthebee** [comment]
Closing the issue for now
